using System.Collections.Generic;
using System.Linq;

namespace ProjectEuler
{
    /// <summary>
    /// Problem 2: Even Fibonacci numbers
    /// https://projecteuler.net/problem=2
    /// 
    /// Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be:
    /// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    /// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    /// </summary>
    public class EvenFibonacciNumbers
    {
        private readonly IList<int> _fibonacciList = new List<int> {1, 2};

        public int SumOfEvenNumbers(int inclusiveUpper)
        {
            return FindFibonacciSequence(inclusiveUpper).Where(x => x%2 == 0).Sum();
        }

        public IEnumerable<int> FindFibonacciSequence(int inclusiveUpper)
        {
            if (inclusiveUpper <= 2)
                return _fibonacciList.Take(inclusiveUpper);

            while (_fibonacciList.Last() < inclusiveUpper)
            {
                var nextFibonacciNumber = _fibonacciList[_fibonacciList.Count - 2] + _fibonacciList.Last();
                _fibonacciList.Add(nextFibonacciNumber);
            }

            return _fibonacciList.Where(x => x <= inclusiveUpper);
        }
    }
}